// FBA DASHBOARD API v10
var CONFIG={sheets:{main:'1F1hSU9znhuFlHSp1Ql-2g4-VwQrtRkPUBQzgZrQwdI0',fees:'1o3knUNKth0ehblfX-tsPXTpP3GEW5ms4S72Dyz5eDu0',sales:'1Sk6cEBn16WQNkn_h2hFWFUm2nM4w8KYT5Sedv1zUp6E',summary:'14W3T-O3q5bVYF5PlMbueozyYB5z3tzCPHxhtTAcJVlM',inbound:'1CdpmwuSHPtq3IuG6y3w7qn1bFTf1qulm7kaKRqnaSDc',coreDaily:'1c2PKs1yU2DCWvIVQSnJuLv9c-nm7C7M3OLwngEV1Vqw',bundleDaily:'1EWXEaV3f-uNTspWdPDdgXR2GLzQnZVbuJQP4lnZsYT4',abc:'1dhmeqf_7WoF6oeP5OYkGUzWWgqfAPgzrXAyg5h_1k2s'},tabs:{cores:'Core Products',bundles:'Bundle SKUs',vendors:'Vendor List',fees:'Current Fees by ASIN',sales:'Sales by Period by ASIN',dashboard:'Dashboard_Agg',bundleSales:'Monthly Bundle Sales',priceHist:'Monthly Price History',bundleInv:'Monthly Bundle Inventory',coreInv:'Monthly Core Inventory',inbound:'Final Arrival Date for Imports',coreDailyHist:'Inventory History',bundleDailyHist:'Inventory History',abcAnalysis:'ABC Analysis',abcTrends:'ABC Trends'},refreshMinutes:15,cacheTTL:1200};

function doGet(e){var p=e?e.parameter:{};var a=p.action||'live';var cb=p.callback;var r;try{switch(a){case'live':r=getLiveData();break;case'history':r=getHistoryData();break;case'daily':r=getDailyData();break;case'all':r=getLiveData();r.history=getHistoryData();break;case'refresh':refreshAllCaches();r={status:'ok'};break;case'status':r={timestamp:getTS(),note:'v10'};break;default:r={error:'Unknown: '+a}}}catch(err){r={error:err.message}}var j=JSON.stringify(r);if(cb)return ContentService.createTextOutput(cb+'('+j+')').setMimeType(ContentService.MimeType.JAVASCRIPT);return ContentService.createTextOutput(j).setMimeType(ContentService.MimeType.JSON)}

var CK=95000;
function cSet(k,d){var c=CacheService.getScriptCache();var j=JSON.stringify(d);var n=Math.ceil(j.length/CK);var p={};p[k+'_n']=String(n);for(var i=0;i<n;i++)p[k+'_'+i]=j.substring(i*CK,(i+1)*CK);var e=Object.entries(p);for(var i=0;i<e.length;i+=25)c.putAll(Object.fromEntries(e.slice(i,i+25)),CONFIG.cacheTTL)}
function cGet(k){var c=CacheService.getScriptCache();var ns=c.get(k+'_n');if(!ns)return null;var n=parseInt(ns);var ks=[];for(var i=0;i<n;i++)ks.push(k+'_'+i);var v=c.getAll(ks);var j='';for(var i=0;i<n;i++){var x=v[k+'_'+i];if(!x)return null;j+=x}try{return JSON.parse(j)}catch(e){return null}}
function getTS(){return CacheService.getScriptCache().get('_ts')||''}
function num(v){if(v===''||v==null)return 0;var n=Number(v);return isNaN(n)?0:Math.round(n*1000)/1000}
function str(v){return v==null?'':String(v).trim()}
function monthStr(v){if(!v)return'';if(v instanceof Date){if(isNaN(v.getTime()))return'';var y=v.getFullYear();var m=v.getMonth()+1;return y+'-'+(m<10?'0'+m:''+m)}var s=String(v).trim();if(/^\d{4}-\d{2}$/.test(s))return s;try{var d=new Date(s);if(!isNaN(d.getTime())){var y=d.getFullYear();var m=d.getMonth()+1;return y+'-'+(m<10?'0'+m:''+m)}}catch(e){}return s}
function dateStr(v){if(!v)return'';if(v instanceof Date){if(isNaN(v.getTime()))return'';var y=v.getFullYear();var m=v.getMonth()+1;var d=v.getDate();return y+'-'+(m<10?'0'+m:''+m)+'-'+(d<10?'0'+d:''+d)}var s=String(v).trim();try{var dt=new Date(s);if(!isNaN(dt.getTime())){var y=dt.getFullYear();var mo=dt.getMonth()+1;var d=dt.getDate();return y+'-'+(mo<10?'0'+mo:''+mo)+'-'+(d<10?'0'+d:''+d)}}catch(e){}return s}
function getYM(v){if(!v)return null;var d=v instanceof Date?v:new Date(v);if(isNaN(d.getTime()))return null;return{y:d.getFullYear(),m:d.getMonth()+1}}
function readSheet(sid,tab){try{var s=SpreadsheetApp.openById(sid).getSheetByName(tab);if(!s){Logger.log('Tab not found: '+tab+' in '+sid);return{h:[],r:[]}}var d=s.getDataRange().getValues();var hi=0;for(var i=0;i<Math.min(d.length,5);i++){var row=d[i];var found=false;for(var j=0;j<row.length;j++){var cs=String(row[j]);if(cs.indexOf('Core')>=0||cs.indexOf('JLS')>=0||cs.indexOf('Vendor')>=0||cs.indexOf('Cases')>=0||cs.indexOf('Month')>=0||cs.indexOf('Units')>=0||cs.indexOf('Date')>=0||cs.indexOf('Unique')>=0||cs.indexOf('ASIN')>=0||cs.indexOf('Revenue')>=0){found=true;break}}if(found){hi=i;break}}return{h:d[hi]||[],r:d.slice(hi+1)}}catch(e){Logger.log('Read err ['+tab+']: '+e.message);return{h:[],r:[]}}}
function cm(h){var m={};for(var i=0;i<h.length;i++)m[String(h[i]).trim()]=i;return m}
function g(r,c,n){var i=c[n];return i!==undefined?r[i]:undefined}

function processCores(){var d=readSheet(CONFIG.sheets.main,CONFIG.tabs.cores);var c=cm(d.h);return d.r.filter(function(r){return r[c['Core Number']]}).map(function(r){return{id:str(g(r,c,'Core Number')),ti:str(g(r,c,'Internal Title')),vsku:str(g(r,c,'Vendor SKU')),dsr:num(g(r,c,'DSR')),d1:num(g(r,c,'1 Day DSR')),d3:num(g(r,c,'3 Day DSR')),d7:num(g(r,c,'7 Day DSR')),doc:num(g(r,c,'Complete DOC')),cash:num(g(r,c,'Cash Invested')),own:num(g(r,c,'All-In Owned Pieces')),raw:num(g(r,c,'Raw Pieces')),inb:num(g(r,c,'Inbound Pieces')),pp:num(g(r,c,'Pre-Processed Pieces')),jfn:num(g(r,c,'JFN Pieces')),pq:num(g(r,c,'Processing Queue Pieces')),ji:num(g(r,c,'JLS Inbound to FBA Pieces')),fba:num(g(r,c,'Total FBA & Inbound Pieces')),jlsList:str(g(r,c,'Attached JLS #s')),ven:str(g(r,c,'Vendor')),vou:str(g(r,c,'Vendor Order Unit')),casePack:num(g(r,c,'Vendor Case Pack')),cost:num(g(r,c,'Latest Vendor Cost per Piece')),moq:num(g(r,c,'MOQ (Pieces)')),buf:num(g(r,c,'Buffer Days')),minLevel:num(g(r,c,'Minimum Level')),note:str(g(r,c,'Note for Next Order')),blendedCost:num(g(r,c,'Blended Vendor Cost per Piece')),cat:str(g(r,c,'Core Category')),tag1:str(g(r,c,'Tag 1')),tag2:str(g(r,c,'Tag 2')),hazmat:str(g(r,c,'Hazmat')),active:str(g(r,c,'Active')),ignoreUntil:str(g(r,c,'Ignore Until')),visible:str(g(r,c,'Visible')),restockable:str(g(r,c,'Restockable'))}})}
function processBundles(){var d=readSheet(CONFIG.sheets.main,CONFIG.tabs.bundles);var c=cm(d.h);return d.r.filter(function(r){return r[c['JLS #']]}).map(function(r){return{j:str(g(r,c,'JLS #')),t:str(g(r,c,'Short Title')),cd:num(g(r,c,'Complete DSR')),fbaDsr:num(g(r,c,'FBA DSR')),d7fba:num(g(r,c,'7 Day FBA DSR')),d7comp:num(g(r,c,'7 Day Complete DSR')),d1:num(g(r,c,'1 Day FBA DSR')),d3:num(g(r,c,'3 Day FBA DSR')),cogs:num(g(r,c,'COGS')),pdmtCogs:num(g(r,c,'PDMT COGS')),aicogs:num(g(r,c,'AICOGS')),cash:num(g(r,c,'Cash Invested')),doc:num(g(r,c,'Complete DOC')),fibDoc:num(g(r,c,'FIBDOC')),fibInv:num(g(r,c,'FIB Inventory')),scInv:num(g(r,c,'SC Inventory')),reserved:num(g(r,c,'Reserved')),inbound:num(g(r,c,'Inbound')),brand:str(g(r,c,'Brand')),active:str(g(r,c,'Active')),tag1:str(g(r,c,'Tag 1')),replenTag:str(g(r,c,'Replen Tag')),ignoreUntil:str(g(r,c,'Ignore Until')),asin:str(g(r,c,'ASIN')),bundleCode:str(g(r,c,'Bundle Code')),numCores:num(g(r,c,'Number of Cores')),vendors:str(g(r,c,'Vendors')),core1:str(g(r,c,'Core 1'))}})}
function processVendors(){var d=readSheet(CONFIG.sheets.main,CONFIG.tabs.vendors);var c=cm(d.h);return d.r.filter(function(r){return r[c['Vendor Name']]}).map(function(r){return{name:str(g(r,c,'Vendor Name')),code:str(g(r,c,'Short Code')),vou:str(g(r,c,'Vendor Order Unit')),dead:str(g(r,c,'Dead Vendor or Supply Vendor')),lt:num(g(r,c,'Lead Time (Days)')),bizDays:num(g(r,c,'Business Days to Receive')),moqDollar:num(g(r,c,'$ MOQ')),moqCases:num(g(r,c,'Cases MOQ')),payment:str(g(r,c,'Payment Method')),terms:str(g(r,c,'Terms')),orderMethod:str(g(r,c,'Order Method')),country:str(g(r,c,'Country')),contactName:str(g(r,c,'Order Contact Name')),contactPhone:str(g(r,c,'Order Contact Phone')),contactEmail:str(g(r,c,'Order Contact Email')),address:str(g(r,c,'Combined Address')),address1:str(g(r,c,'Address 1')),address2:str(g(r,c,'Address 2')),city:str(g(r,c,'City')),state:str(g(r,c,'State')),zip:str(g(r,c,'Zip'))}})}
function processSales(){var d=readSheet(CONFIG.sheets.sales,CONFIG.tabs.sales);var c=cm(d.h);return d.r.filter(function(r){return r[c['JLS #']]}).map(function(r){return{j:str(g(r,c,'JLS #')),t:str(g(r,c,'Short Title')),asin:str(g(r,c,'ASIN')),tmU:num(g(r,c,'This Month Units')),tmR:num(g(r,c,'This Month Revenue')),tmP:num(g(r,c,'This Month Profit')),lmU:num(g(r,c,'Last Month Units')),lmR:num(g(r,c,'Last Month Revenue')),lmP:num(g(r,c,'Last Month Profit')),ydU:num(g(r,c,'Yesterday Units')),ydR:num(g(r,c,'Yesterday Revenue')),l7U:num(g(r,c,'Last 7 Days Units')),l7R:num(g(r,c,'Last 7 Days Revenue')),l7P:num(g(r,c,'Last 7 Days Profit')),l28U:num(g(r,c,'Last 28 Days Units')),l28R:num(g(r,c,'Last 28 Days Revenue')),l28P:num(g(r,c,'Last 28 Days Profit')),l84U:num(g(r,c,'Last 84 Days Units')),l84R:num(g(r,c,'Last 84 Days Revenue')),l365U:num(g(r,c,'Last 365 Days Units')),l365R:num(g(r,c,'Last 365 Days Revenue')),tyU:num(g(r,c,'This Year Units')),tyR:num(g(r,c,'This Year Revenue')),tyP:num(g(r,c,'This Year Profit')),lyU:num(g(r,c,'Last Year Units')),lyR:num(g(r,c,'Last Year Revenue')),lyP:num(g(r,c,'Last Year Profit')),ltU:num(g(r,c,'Lifetime Units')),ltR:num(g(r,c,'Lifetime Revenue')),ltP:num(g(r,c,'Lifetime Profit'))}})}
function processFees(){var d=readSheet(CONFIG.sheets.fees,CONFIG.tabs.fees);var c=cm(d.h);return d.r.filter(function(r){return r[c['JLS #']]}).map(function(r){return{j:str(g(r,c,'JLS #')),asin:str(g(r,c,'ASIN')),t:str(g(r,c,'Short Title')),pr:num(g(r,c,'Price')),refFee:num(g(r,c,'Referral Fee')),fbaFee:num(g(r,c,'FBA Fee')),jfnFee:num(g(r,c,'JFN Fee')),totalFee:num(g(r,c,'Total Fee')),netRev:num(g(r,c,'Net Revenue')),pdmtCogs:num(g(r,c,'PDMT COGS')),aicogs:num(g(r,c,'AICOGS')),gp:num(g(r,c,'Gross Profit')),bePr:num(g(r,c,'Breakeven Price')),beAcos:num(g(r,c,'Breakeven ACoS')),dubAcos:num(g(r,c,'Double Up ACoS'))}})}
function processInbound(){var d=readSheet(CONFIG.sheets.inbound,CONFIG.tabs.inbound);var c=cm(d.h);return d.r.filter(function(r){var cv=g(r,c,'Core #');return cv&&String(cv).trim()!==''}).map(function(r){return{core:str(g(r,c,'Core #')),name:str(g(r,c,'Name')),vendor:str(g(r,c,'Vendor')),shortTitle:str(g(r,c,'Short Title')),vsku:str(g(r,c,'Vendor SKU')),pieces:num(g(r,c,'Pieces Ordered')),cases:num(g(r,c,'Cases Ordered')),price:num(g(r,c,'Piece Price')),terms:str(g(r,c,'Terms')),orderNum:str(g(r,c,'Order #')),eta:dateStr(g(r,c,'Final Arrival Date')),origEta:dateStr(g(r,c,'Expected Arrival')),piecesMissing:num(g(r,c,'Pieces Missing'))}})}

// === ABC DATA ===
function processABCAnalysis(){var d=readSheet(CONFIG.sheets.abc,CONFIG.tabs.abcAnalysis);var c=cm(d.h);return d.r.filter(function(r){return r[c['JLS #']]}).map(function(r){return{j:str(g(r,c,'JLS #')),asin:str(g(r,c,'ASIN')),t:str(g(r,c,'Short Title')),rev:num(g(r,c,'Revenue')),revCum:num(g(r,c,'Rev Cum%')),revABC:str(g(r,c,'Rev ABC')),profit:num(g(r,c,'Profit')),profCum:num(g(r,c,'Prof Cum%')),profABC:str(g(r,c,'Prof ABC')),units:num(g(r,c,'Units')),unitsCum:num(g(r,c,'Units Cum%')),unitsABC:str(g(r,c,'Units ABC'))}})}
function processABCTrends(){var d=readSheet(CONFIG.sheets.abc,CONFIG.tabs.abcTrends);var c=cm(d.h);return d.r.filter(function(r){return r[c['JLS #']]}).map(function(r){return{j:str(g(r,c,'JLS #')),asin:str(g(r,c,'ASIN')),t:str(g(r,c,'Short Title')),q4_24:str(g(r,c,'2024 Q4')),q1_25:str(g(r,c,'2025 Q1')),q2_25:str(g(r,c,'2025 Q2')),q3_25:str(g(r,c,'2025 Q3')),q4_25:str(g(r,c,'2025 Q4')),q1_26:str(g(r,c,'2026 Q1')),movement:str(g(r,c,'Movement'))}})}

// === DAILY DATA (last 14 days, all columns) ===
function getDailyData(){
  var cutoff=new Date();cutoff.setDate(cutoff.getDate()-14);
  var cd=readSheet(CONFIG.sheets.coreDaily,CONFIG.tabs.coreDailyHist);var cc=cm(cd.h);var coreDays=[];
  for(var i=0;i<cd.r.length;i++){var r=cd.r[i];var dv=g(r,cc,'Date');if(!dv)continue;var dt=dv instanceof Date?dv:new Date(dv);if(isNaN(dt.getTime())||dt<cutoff)continue;
    coreDays.push({date:dateStr(dv),core:str(g(r,cc,'Core Number')),dsr:num(g(r,cc,'DSR')),d1:num(g(r,cc,'1 Day DSR')),d3:num(g(r,cc,'3 Day DSR')),d7:num(g(r,cc,'7 Day DSR')),doc:num(g(r,cc,'Complete DOC')),cash:num(g(r,cc,'Cash Invested')),own:num(g(r,cc,'All-In Owned Pieces')),raw:num(g(r,cc,'Raw Pieces')),inb:num(g(r,cc,'Inbound Pieces')),pp:num(g(r,cc,'Pre-Processed Pieces')),jfn:num(g(r,cc,'JFN Pieces')),pq:num(g(r,cc,'Processing Queue Pieces')),ji:num(g(r,cc,'JLS Inbound to FBA Pieces')),fba:num(g(r,cc,'Total FBA & Inbound Pieces'))});}
  var bd=readSheet(CONFIG.sheets.bundleDaily,CONFIG.tabs.bundleDailyHist);var bc=cm(bd.h);var bundleDays=[];
  for(var i=0;i<bd.r.length;i++){var r=bd.r[i];var dv=g(r,bc,'Date');if(!dv)continue;var dt=dv instanceof Date?dv:new Date(dv);if(isNaN(dt.getTime())||dt<cutoff)continue;
    bundleDays.push({date:dateStr(dv),j:str(g(r,bc,'JLS #')),dsr:num(g(r,bc,'Complete DSR')),d7:num(g(r,bc,'7 Day Complete DSR')),d1:num(g(r,bc,'1 Day FBA DSR')),d3:num(g(r,bc,'3 Day FBA DSR')),doc:num(g(r,bc,'Complete DOC')),fib:num(g(r,bc,'FIB Inventory')),sc:num(g(r,bc,'SC Inventory')),res:num(g(r,bc,'Reserved')),inb:num(g(r,bc,'Inbound')),cash:num(g(r,bc,'Cash Invested'))});}
  return{coreDays:coreDays,bundleDays:bundleDays};
}

// === HISTORY ===
function processBundleSales(){var d=readSheet(CONFIG.sheets.summary,CONFIG.tabs.bundleSales);var c=cm(d.h);return d.r.filter(function(r){return r[c['JLS #']]}).map(function(r){return{j:str(g(r,c,'JLS #')),month:monthStr(g(r,c,'Month')),y:num(g(r,c,'Year')),m:num(g(r,c,'Mo')),units:num(g(r,c,'Units')),rev:num(g(r,c,'Revenue')),profit:num(g(r,c,'Profit')),avgPrice:num(g(r,c,'Avg Price'))}})}
function processCoreInvSummary(){var d=readSheet(CONFIG.sheets.summary,CONFIG.tabs.coreInv);var c=cm(d.h);return d.r.filter(function(r){return r[c['Core']]}).map(function(r){return{core:str(g(r,c,'Core')),month:monthStr(g(r,c,'Month')),y:num(g(r,c,'Year')),m:num(g(r,c,'Mo')),avgDsr:num(g(r,c,'Avg DSR')),avg7d:num(g(r,c,'Avg 7D DSR')),avgDoc:num(g(r,c,'Avg DOC')),avgOwn:num(g(r,c,'Avg All-In Own')),avgFba:num(g(r,c,'Avg FBA')),oosDays:num(g(r,c,'OOS Days')),newOos:num(g(r,c,'New OOS Events')),dataDays:num(g(r,c,'Data Days'))}})}
function processBundleInvSummary(){var d=readSheet(CONFIG.sheets.summary,CONFIG.tabs.bundleInv);var c=cm(d.h);return d.r.filter(function(r){return r[c['JLS #']]}).map(function(r){return{j:str(g(r,c,'JLS #')),month:monthStr(g(r,c,'Month')),y:num(g(r,c,'Year')),m:num(g(r,c,'Mo')),avgDsr:num(g(r,c,'Avg DSR')),avg7d:num(g(r,c,'Avg 7D DSR')),avgDoc:num(g(r,c,'Avg DOC')),avgFib:num(g(r,c,'Avg FIB Inv')),dataDays:num(g(r,c,'Data Days'))}})}
function processPriceHist(){var d=readSheet(CONFIG.sheets.summary,CONFIG.tabs.priceHist);var c=cm(d.h);return d.r.filter(function(r){return r[c['JLS #']]}).map(function(r){return{j:str(g(r,c,'JLS #')),month:monthStr(g(r,c,'Month')),y:num(g(r,c,'Year')),m:num(g(r,c,'Mo')),avgPrice:num(g(r,c,'Avg Price')),avgGp:num(g(r,c,'Avg GP')),avgFee:num(g(r,c,'Avg Total Fee')),dataPoints:num(g(r,c,'Data Points'))}})}

function aggregateCoreDailyByMonth(){var d=readSheet(CONFIG.sheets.coreDaily,CONFIG.tabs.coreDailyHist);var c=cm(d.h);var b={};for(var i=0;i<d.r.length;i++){var r=d.r[i];var dv=g(r,c,'Date');var ci=str(g(r,c,'Core Number'));if(!ci||!dv)continue;var ym=getYM(dv);if(!ym)continue;var k=ci+'|'+ym.y+'|'+ym.m;if(!b[k])b[k]={core:ci,y:ym.y,m:ym.m,ds:0,d7s:0,docs:0,os:0,fs:0,oos:0,no:0,n:0};var x=b[k];x.ds+=num(g(r,c,'DSR'));x.d7s+=num(g(r,c,'7 Day DSR'));x.docs+=num(g(r,c,'Complete DOC'));x.os+=num(g(r,c,'All-In Owned Pieces'));x.fs+=num(g(r,c,'Total FBA & Inbound Pieces'));var ov=g(r,c,'Out of Stock');if(ov==='Yes'||ov===true||ov===1||ov==='TRUE')x.oos++;var nv=g(r,c,'New Out of Stock');if(nv==='Yes'||nv===true||nv===1||nv==='TRUE')x.no++;x.n++}var res=[];var ks=Object.keys(b);for(var i=0;i<ks.length;i++){var x=b[ks[i]];res.push({core:x.core,month:x.y+'-'+(x.m<10?'0'+x.m:''+x.m),y:x.y,m:x.m,avgDsr:Math.round(x.ds/x.n*1000)/1000,avg7d:Math.round(x.d7s/x.n*1000)/1000,avgDoc:Math.round(x.docs/x.n*1000)/1000,avgOwn:Math.round(x.os/x.n*1000)/1000,avgFba:Math.round(x.fs/x.n*1000)/1000,oosDays:x.oos,newOos:x.no,dataDays:x.n})}return res}
function aggregateBundleDailyByMonth(){var d=readSheet(CONFIG.sheets.bundleDaily,CONFIG.tabs.bundleDailyHist);var c=cm(d.h);var b={};for(var i=0;i<d.r.length;i++){var r=d.r[i];var dv=g(r,c,'Date');var jl=str(g(r,c,'JLS #'));if(!jl||!dv)continue;var ym=getYM(dv);if(!ym)continue;var k=jl+'|'+ym.y+'|'+ym.m;if(!b[k])b[k]={j:jl,y:ym.y,m:ym.m,ds:0,d7s:0,docs:0,fs:0,n:0};var x=b[k];x.ds+=num(g(r,c,'Complete DSR'));x.d7s+=num(g(r,c,'7 Day Complete DSR'));x.docs+=num(g(r,c,'Complete DOC'));x.fs+=num(g(r,c,'FIB Inventory'));x.n++}var res=[];var ks=Object.keys(b);for(var i=0;i<ks.length;i++){var x=b[ks[i]];res.push({j:x.j,month:x.y+'-'+(x.m<10?'0'+x.m:''+x.m),y:x.y,m:x.m,avgDsr:Math.round(x.ds/x.n*1000)/1000,avg7d:Math.round(x.d7s/x.n*1000)/1000,avgDoc:Math.round(x.docs/x.n*1000)/1000,avgFib:Math.round(x.fs/x.n*1000)/1000,dataDays:x.n})}return res}
function mergeCoreInv(s,d){var e={};for(var i=0;i<s.length;i++)e[s[i].core+'|'+s[i].y+'|'+s[i].m]=true;var m=s.slice();for(var i=0;i<d.length;i++){if(!e[d[i].core+'|'+d[i].y+'|'+d[i].m])m.push(d[i])}return m}
function mergeBundleInv(s,d){var e={};for(var i=0;i<s.length;i++)e[s[i].j+'|'+s[i].y+'|'+s[i].m]=true;var m=s.slice();for(var i=0;i<d.length;i++){if(!e[d[i].j+'|'+d[i].y+'|'+d[i].m])m.push(d[i])}return m}

function refreshAllCaches(){var st=new Date();Logger.log('=== REFRESH v10 ===');
  try{cSet('cores',processCores())}catch(e){Logger.log('ERR cores:'+e.message)}
  try{cSet('bundles',processBundles())}catch(e){Logger.log('ERR bundles:'+e.message)}
  try{cSet('vendors',processVendors())}catch(e){Logger.log('ERR vendors:'+e.message)}
  try{cSet('sales',processSales())}catch(e){Logger.log('ERR sales:'+e.message)}
  try{cSet('fees',processFees())}catch(e){Logger.log('ERR fees:'+e.message)}
  try{cSet('inbound',processInbound())}catch(e){Logger.log('ERR inbound:'+e.message)}
  try{cSet('abcA',processABCAnalysis())}catch(e){Logger.log('ERR abcA:'+e.message)}
  try{cSet('abcT',processABCTrends())}catch(e){Logger.log('ERR abcT:'+e.message)}
  try{cSet('h_bsales',processBundleSales())}catch(e){Logger.log('ERR h_bsales:'+e.message)}
  try{cSet('h_price',processPriceHist())}catch(e){Logger.log('ERR h_price:'+e.message)}
  try{var cs=processCoreInvSummary();var cd=aggregateCoreDailyByMonth();cSet('h_coreinv',mergeCoreInv(cs,cd))}catch(e){Logger.log('ERR h_coreinv:'+e.message)}
  try{var bs=processBundleInvSummary();var bd=aggregateBundleDailyByMonth();cSet('h_binv',mergeBundleInv(bs,bd))}catch(e){Logger.log('ERR h_binv:'+e.message)}
  CacheService.getScriptCache().put('_ts',new Date().toISOString(),CONFIG.cacheTTL);
  Logger.log('=== DONE: '+((new Date()-st)/1000).toFixed(1)+'s ===');
}

function getLiveData(){var c=cGet('cores');if(!c){refreshAllCaches();c=cGet('cores')}return{cores:c||[],bundles:cGet('bundles')||[],vendors:cGet('vendors')||[],sales:cGet('sales')||[],fees:cGet('fees')||[],inbound:cGet('inbound')||[],abcA:cGet('abcA')||[],abcT:cGet('abcT')||[],timestamp:getTS()}}
function getHistoryData(){var b=cGet('h_bsales');if(!b){try{refreshAllCaches();b=cGet('h_bsales')}catch(e){b=[]}}return{bundleSales:b||[],coreInv:cGet('h_coreinv')||[],bundleInv:cGet('h_binv')||[],priceHist:cGet('h_price')||[]}}
function setupTrigger(){var t=ScriptApp.getProjectTriggers();for(var i=0;i<t.length;i++){if(t[i].getHandlerFunction()==='refreshAllCaches')ScriptApp.deleteTrigger(t[i])}ScriptApp.newTrigger('refreshAllCaches').timeBased().everyMinutes(CONFIG.refreshMinutes).create();Logger.log('Trigger created');refreshAllCaches()}
